### ISSUE TITLE
Screenshot logging and log4j2 settings

### ISSUE THREAD

**Issue by apsharma** [reportportal/examples-java#57]
I am noticing that deviating from these [suggested](https://github.com/reportportal/logger-java-log4j) settings prevents screenshots from getting reported to or sent to reportportal server. Could someone help me figure out what is causing this behavior ? or what am I not doing right ? 

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration packages="com.epam.ta.reportportal.log4j.appender" status="WARN" monitorInterval="5">
    <Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" />
        </Console>
        <ReportPortalLog4j2Appender name="ReportPortalAppender">
            <PatternLayout
                    pattern="%d{yyy-MM-dd HH:mm:ss.SSS}  [%t] %-5level %logger{36} - %msg%n%throwable"/>
        </ReportPortalLog4j2Appender>
    </Appenders>
    <Loggers>
        <Logger name="com.company.project" level="DEBUG">
            <AppenderRef ref="ConsoleAppender"/>
        </Logger>
        <Root level="TRACE">
            <AppenderRef ref="ReportPortalAppender"/>
        </Root>
        <Logger name="com.epam.reportportal.service" level="WARN" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
        <Logger name="com.epam.reportportal.utils" level="WARN" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
    </Loggers>
</Configuration>
```

I tried adding an additional logger (below) so that I could see all reportportal related logs and get some more details ..and for some odd reason that too prevented screenshots from being sent over ? 
```
        <Logger name="com.epam.reportportal" level="DEBUG" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
```

BTW, I don't need a ton of screenshot logging (send screenshots only on failures during a UI test) so this is how I am reporting/sending screenshots/files `ReportPortal.emitLog("Failure Screenshot", "ERROR", testName, errFileName);`

**Comment by HardNorth** [comment]
@apsharma I'm not getting how your configuration file looks like. Can you share what are you trying to do?

**Comment by HardNorth** [comment]
I reviewed our Log4j configuration and it works as expected: https://github.com/reportportal/examples-java/blob/master/example-testng-log4j/src/main/resources/log4j2.xml

I don't see any more points to improve. And the issue is abandoned.
