### ISSUE TITLE
examples and documentation for java-client 

### ISSUE THREAD

**Issue by shlomitubul** [reportportal/examples-java#58]
Hi, 
I'm looking for an example or some documentation about java-client (without any testing framework) usage.
(Form what I see there example for agent mainly)

**Comment by HardNorth** [comment]
Each java agent is an example itself, E.G. JUnit 5:
https://github.com/reportportal/agent-java-junit5/blob/develop/src/main/java/com/epam/reportportal/junit5/ReportPortalExtension.java
Or Cucumber:
https://github.com/reportportal/agent-java-cucumber6/blob/develop/src/main/java/com/epam/reportportal/cucumber/AbstractReporter.java

There is no single approach on agent implementation: all of them different. Therefore no documentation available. Use code and javadoc to get idea of what each method does.
