### ISSUE TITLE
[ERROR] Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener #84

### ISSUE THREAD

**Issue by gargsachin13** [reportportal/examples-java#59]
**Describe the bug**

**Steps to Reproduce**

Added dependencies
Tried adding listener is xml/ Using @Listeners annotation, but still getting error

**Expected behavior**

**Actual behavior**
What actually happened.

**Dependency versions**
 <dependencies>
     
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.5</version>
            <scope>test</scope>
        </dependency>
      
      <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.4</version>
        </dependency>
        
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.5.1</version>
        </dependency>
     
        <dependency>  
            <groupId>log4j</groupId>  
            <artifactId>log4j</artifactId>  
            <version>1.2.17</version>  
        </dependency>
     
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>4.0.9</version>
        </dependency>
     
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports-testng-adapter</artifactId>
            <version>1.0.3</version>
        </dependency>
<dependency>
	<groupId>com.epam.reportportal</groupId>
	<artifactId>agent-java-testng</artifactId>
	<version>5.1.2</version>
</dependency>
	
	
	<dependency>
		<groupId>com.epam.reportportal</groupId>
		<artifactId>logger-java-log4j</artifactId>
		<version>5.1.4</version>
	</dependency>
   
      <dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-simple</artifactId>
  <version>1.7.21</version>
</dependency>

   </dependencies>
**Additional context**

**Comment by HardNorth** [comment]
@gargsachin13 Any stacktrace?

**Comment by HardNorth** [comment]
Abandoned
