### ISSUE TITLE
RestAssured Logging | java.lang.NoClassDefFoundError: Could not initialize class com.epam.reportportal.restassured.ReportPortalRestAssuredLoggin gFilter

### ISSUE THREAD

**Issue by bhargavkumar-65** [reportportal/examples-java#60]
Hi Team,
Not able to use RestAssured logging as described in example getting below error.
java.lang.NoClassDefFoundError: Could not initialize class com.epam.reportportal.restassured.ReportPortalRestAssuredLoggin
gFilter

please check
cc: @HardNorth

**Comment by HardNorth** [comment]
@bhargavkumar-65 Please use our templates to post an issue, I count this issue with no details as contempt. Also, it requires the latest rest-assured version. Also, seek in your configurations, since our examples work fine, you can check it with `mvn test` in `example-testng-logback` module.
