### ISSUE TITLE
Unable to send attachment to ReportPortal

### ISSUE THREAD

**Issue by bhagyaISS** [reportportal/examples-java#75]
**Describe the bug**
I am unable to send scrrenshotOnFailure as an attachment to Report Portal.

**Steps to Reproduce**
1. Logger used to send attachment to reportPortal : public static final Logger logger = LoggerFactory.getLogger("binary_data_logger");
2. We are sending compressed file as, reportportal doesn't support file greater than specific size.
3. Code snippet:
String screenShotFilePathCompressed = attachments.get(1);
 try {
            logger.info("RP_MESSAGE#FILE#{}#{}", screenShotFilePathCompressed, "Attachment");
            logger.info("File Location : " + screenShotFilePath);
        } catch (Exception e) {
            logger.info("Test failed, cannot attach screenshot");
        }

**Expected behavior**
To log screenshot as attachment into report portal

**Actual behavior**
Screenshot not attached.

**Dependency versions**
Include version info of the following libraries: 
selenium-java: 3.141.59
Java:11

<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>5.1.0</version>
        </dependency>

<dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.1.8</version>
        </dependency>

<dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.20.0</version>
        </dependency>

<dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.20.0</version>
        </dependency>

**Additional context**

Log4j2.xml configuration as below:

<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn">
    <Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%d{ISO8601} [%t] %-5p (%F\:%L) - %m%n"/>
        </Console>
        <ReportPortalLog4j2Appender name="ReportPortalAppender">
            <PatternLayout
                    pattern="%d{ISO8601} [%t] %-5p (%F\:%L) - %m%n"/>
        </ReportPortalLog4j2Appender>
    </Appenders>
    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Root>
        <Logger name="com.epam.reportportal" level="INFO" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
        <Logger name="binary_data_logger" level="INFO" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>
    </Loggers>
</Configuration>

**Comment by HardNorth** [comment]
@bhagyaISS You didn't provide any Log4j configuration actually. And I recently updated and tested Log4j integration on our examples, it is working.
So, please do the following things:
1. Provide Log4j2.xml config and Log4j2 dependencies, which you use.
2. Check out our examples:
    * An example test: https://github.com/reportportal/examples-java/blob/master/example-testng-log4j/src/main/java/com/epam/reportportal/example/testng/log4j/extension/ScreenshotOnFailureTestExtensionTest.java
    * Log4j2 configuration: https://github.com/reportportal/examples-java/blob/master/example-testng-log4j/src/main/resources/log4j2.xml
    * Dependencies: https://github.com/reportportal/examples-java/blob/master/example-testng-log4j/pom.xml#L43-L58

**Comment by HardNorth** [comment]
Abandoned
